stages:
  - test

test:
  stage: test
  script:
    - apt-get update -qy
    - apt-get install -y python-dev python-pip
    - pip install -r requirements.txt
    - pip install flake8
    - flake8 . --select=E9,F63,F7,F82 --show-source
    - flake8 . --exit-zero --max-complexity=10 --max-line-length=127
    - export AUTOMX2_CONF='tests/unittest.conf'
    - python -m unittest discover tests/
